# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.ImageField(blank=True, upload_to='organisation_image'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
    ]
