# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20180505_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='image',
        ),
    ]
