# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_remove_organisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organisations_image'),
        ),
    ]
