# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_organisation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='nom',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
