# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 06:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(max_length=50, verbose_name='META')),
                ('nom', models.TextField(verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(max_length=300, verbose_name='En savoir plus : ')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'zones',
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Zone'),
        ),
    ]
