# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_auto_20180505_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organisation'),
        ),
    ]
