# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_auto_20180505_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('FO', 'Forêt'), ('EA', 'Eau'), ('AN', 'Animaux'), ('AI', 'Air'), ('IN', 'Insectes'), ('PL', 'Plantes'), ('RC', 'Rechauffement climatique'), ('NA', 'Aucune')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='projet',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projets.Zone'),
        ),
    ]
