# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-06 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_auto_20180505_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fichier', models.CharField(choices=[('TX', 'Texte'), ('IM', 'Image'), ('PD', 'PDF'), ('AU', 'Autre'), ('FC', 'Feuille de calcul')], default='AU', max_length=2)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=75, null=True)),
                ('ficher', models.FileField(upload_to='soumission')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Projet')),
            ],
            options={
                'verbose_name_plural': 'soumissions',
            },
        ),
    ]
