# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-06 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_soumission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soumission',
            old_name='ficher',
            new_name='fichier',
        ),
    ]
