# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_auto_20180506_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='nom',
            field=models.CharField(default='', max_length=150),
        ),
    ]
